const fs=require('fs'),path=require('path');
const sharp=require('C:/Users/001/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');
(async()=>{
 const before=JSON.parse(fs.readFileSync(path.join(__dirname,'Verification/startup_before.json'))),after=JSON.parse(fs.readFileSync(path.join(__dirname,'Verification/startup_after.json')));
 const all=[before.runs[0],...after.runs],colors=['#df583e','#087fd1','#42a275','#7e58bb'],limit=Math.ceil(Math.max(...all.map(x=>x.totalSeconds)));
 let svg='<svg viewBox="0 0 900 360" role="img" aria-label="修复前后真实渲染进度曲线">';
 for(let i=0;i<=4;i++){let y=310-i*65;svg+=`<path d="M55 ${y}H870" stroke="#d8e7f0"/><text x="4" y="${y+5}" fill="#4b6782">${i*25}%</text>`;}
 for(let i=0;i<=limit;i++){let x=55+i/limit*815;svg+=`<text x="${x}" y="338" text-anchor="middle" fill="#4b6782">${i}s</text>`;}
 all.forEach((run,i)=>{let points=run.frames.map(f=>`${55+f.seconds/limit*815},${310-f.progress*260}`).join(' ');svg+=`<polyline points="${points}" fill="none" stroke="${colors[i]}" stroke-width="3"/>`;});svg+='</svg>';
 for(const name of fs.readdirSync(path.join(__dirname,'Verification')).filter(n=>/^After_startup_\d+_(zero|middle|full)\.png$/.test(n)))
  await sharp(path.join(__dirname,'Verification',name)).resize({width:600,withoutEnlargement:true}).webp({quality:93}).toFile(path.join(__dirname,'Preview',name.replace('.png','.webp')));
 const rows=all.map((r,i)=>`<tr><td style="color:${colors[i]}">${i===0?'修复前':r.name}</td><td>${Math.round(r.firstProgress*100)}%</td><td>${r.zeroVisibleSeconds.toFixed(2)} 秒</td><td>${(r.maximumJump*100).toFixed(2)} 个百分点</td><td>${i===0?'复现跳变':r.passed?'通过':'未通过'}</td></tr>`).join('');
 fs.writeFileSync(path.join(__dirname,'STARTUP_TIMING.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>启动进度修复验证</title><style>body{margin:0;background:#edf7ff;color:#183b5c;font:16px/1.6 system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:26px}section{background:white;padding:24px;border-radius:20px;margin:20px 0}h1{margin:0}svg{width:100%}table{width:100%;border-collapse:collapse}td,th{text-align:left;border-bottom:1px solid #dbeaf5;padding:10px}.shots{display:flex;gap:20px}.shots figure{margin:0;flex:1}.shots img{width:100%;border-radius:12px}small{color:#607a90}</style><main><h1>启动进度修复 · ${after.passed?'验证通过':'待修复'}</h1><p>修复前：0% → 70% → 85% → 100%。现在先显示 0%，随后平滑推进；完成加载并展示 100% 后再进游戏。</p><section>${svg}<table><tr><th>实际 Play 测试</th><th>首次渲染</th><th>0% 可见时长</th><th>最大单帧跳变</th><th>结果</th></tr>${rows}</table><small>曲线来自真实 Canvas 渲染回调，无手动进度注入。截图会带来少量额外耗时，记录时长不作为性能基准。</small></section><section><h2>真实启动帧</h2><div class="shots">${['zero','middle','full'].map((s,i)=>`<figure><img src="Preview/After_startup_0_${s}.webp"><figcaption>${['首次 0%','中间进度','完成 100%'][i]}</figcaption></figure>`).join('')}</div></section><p><a href="REVIEW.html">返回加载页美术验收</a> · <a href="Verification/startup_after.json">查看逐帧记录</a></p></main></html>`);
 for(const name of ['review.cjs','REVIEW.html']){let file=path.join(__dirname,name),s=fs.readFileSync(file,'utf8');s=s.replace('原百分比、加载文字和进度时序保留。收益版进入 RecoveredMain，基础版进入 RecoveredPackaged；使用一次性测试存档。','百分比与加载文字保留；新增 0% 可见停留和平滑推进，100% 后进入对应场景。<a href="STARTUP_TIMING.html">查看真实启动时序验证</a>。');fs.writeFileSync(file,s);}
 console.log('Created real startup timing comparison: '+after.runs.length+' Play sessions.');
})();
