const fs=require('fs'),path=require('path');
const dir=__dirname;
const reports=['SettingsR1','RulesR1'].map(n=>JSON.parse(fs.readFileSync(path.join(dir,n,'Verification/play_mode.json'),'utf8')));
const audit=JSON.parse(fs.readFileSync(path.join(dir,'popup_scope_audit.json'),'utf8'));
const panels=[
 {name:'Settings 设置',target:'SettingsR1/Target.jpg',actual:'SettingsR1/Verification/settings_reference_state_1254.png',portrait:'SettingsR1/Verification/settings_1080x2340.png',jp:'SettingsR1/Verification/settings_jp.png',report:reports[0],assets:['SettingsReskin/Panel','SettingsReskin/Close','SettingsReskin/SwitchOn','SettingsReskin/SwitchOff']},
 {name:'Merge rules 规则',target:'RulesR1/Target.jpg',actual:'RulesR1/Verification/rules_1024x1536.png',portrait:'RulesR1/Verification/rules_1080x2340.png',jp:'RulesR1/Verification/rules_jp.png',report:reports[1],assets:['RulesReskin/Panel','RulesReskin/Close','RulesReskin/Confirm','RulesReskin/ChipAtlas']}
];
fs.writeFileSync(path.join(dir,'POPUPS_REVIEW.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>云朵筹码 · 弹窗换皮验收</title>
<style>*{box-sizing:border-box}body{margin:0;background:#edf7ff;color:#16395c;font:16px/1.65 "Segoe UI","Microsoft YaHei",sans-serif}main{max-width:1320px;margin:auto;padding:34px}h1{font-size:32px;margin:0}p{margin:8px 0 18px}.tag{padding:5px 13px;border-radius:30px;background:#d9f8ea;color:#087154;display:inline-block;margin:4px 8px 4px 0}.muted{color:#5f7790;font-size:14px}nav{display:flex;gap:12px;margin:24px 0}button,select{font:inherit;border:1px solid #b6d6f1;border-radius:12px;padding:10px 20px;background:white;color:#165b9c;cursor:pointer}button.selected{background:#0879d9;color:white}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}figure{margin:0;background:white;border-radius:18px;overflow:hidden;box-shadow:0 8px 28px #113c6112}figcaption{padding:14px 20px;font-weight:650}figure img{width:100%;display:block}.controls{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:18px 0}.assets{display:grid;grid-template-columns:repeat(4,1fr);gap:16px}.asset{min-height:190px;padding:18px;display:flex;align-items:center;justify-content:center;background:#213547;border-radius:14px}.asset.light{background:#fff}.asset img{max-width:100%;max-height:260px;object-fit:contain}details{background:white;padding:16px 22px;border-radius:16px;margin-top:18px}summary{cursor:pointer;font-weight:650}li{margin:5px 0}.result{margin:20px 0;padding:18px 24px;border-left:5px solid #12a572;background:white;border-radius:12px}@media(max-width:780px){main{padding:18px}.grid{grid-template-columns:1fr}.assets{grid-template-columns:1fr 1fr}h1{font-size:25px}}</style>
<main><p class="muted">11_UnityReskin · Unity 2022.3.62f3c1 · 2026-09-16</p><h1>云朵筹码 · 弹窗换皮验收</h1><p>对照用户效果图与 Unity 实际相机渲染。所有交互保留原生 Button，文本可本地化。</p><div><span class="tag">RGBA 透明素材</span><span class="tag">按钮原比例</span><span class="tag">原工程 ${audit.originalFileCount} 文件未变</span><span class="tag">玩法运行时代码未变</span></div>
<nav><button id="settings" onclick="show(0)">Settings 设置</button><button id="rules" onclick="show(1)">Merge rules 规则</button></nav>
<div class="controls"><label>实际画面：<select id="mode" onchange="render()"><option value="actual">参考图比例 · 英文</option><option value="portrait">1080 × 2340 · 英文</option><option value="jp">1080 × 2340 · 日文</option></select></label><span class="muted">点击图片可查看原尺寸</span></div>
<div class="grid"><figure><figcaption>用户参考图</figcaption><a id="targetLink"><img id="target" alt="用户参考图"></a></figure><figure><figcaption>Unity 真实渲染</figcaption><a id="actualLink"><img id="actual" alt="Unity运行画面"></a></figure></div>
<div class="result" id="result"></div><h2>拆分素材 · 透明边缘</h2><div class="controls"><button onclick="document.querySelectorAll('.asset').forEach(x=>x.classList.toggle('light'))">切换深 / 浅检查底色</button><span class="muted">边框、关闭与开关均为独立透明 PNG；背景色不在素材内。</span></div><div class="assets" id="assets"></div>
<details><summary>功能检查记录</summary><ul id="checks"></ul></details><details><summary>范围与还原说明</summary><p>规则弹窗保留原筹码展示动画时序，改为用户指定筹码；设置开关与协议入口保留原逻辑和存档。修正 Canvas 排序后，GM 入口位于弹窗遮罩下，GM 自己的弹窗仍保持顶层。</p><p>面板按参考图制作，英文使用 Nunito，CJK 使用原字体回退。原始效果图含栅格文字与绘制细节，因此字体和局部高光不宣称像素完全相同。游戏背景保持既有 R2 主界面；参考图中的背景模糊不作为新渲染效果加入。</p><p>测试的金额、地区、硬币和开关状态是独立测试数据，不改变真实玩家存档。详细工程范围见 <a href="popup_scope_audit.json">静态检查记录</a>，制作说明见 <a href="POPUPS_README.md">POPUPS_README</a>。</p></details></main>
<script>const panels=${JSON.stringify(panels)};let current=0;function show(i){current=i;document.getElementById('settings').classList.toggle('selected',i===0);document.getElementById('rules').classList.toggle('selected',i===1);render()}function render(){const p=panels[current],mode=document.getElementById('mode').value;document.getElementById('target').src=p.target;document.getElementById('targetLink').href=p.target;document.getElementById('actual').src=p[mode];document.getElementById('actualLink').href=p[mode];document.getElementById('result').textContent=(p.report.passed?'✓ Play Mode 通过':'待修复')+' · '+p.report.checks.length+' 项检查';document.getElementById('checks').innerHTML=p.report.checks.map(x=>'<li>'+x+'</li>').join('');document.getElementById('assets').innerHTML=p.assets.map(x=>'<div class="asset"><a href="../Assets/Resources/'+x+'.png"><img alt="'+x+'" src="../Assets/Resources/'+x+'.png"></a></div>').join('')}show(0)</script></html>`);
console.log('POPUPS_REVIEW.html generated; checks:',reports.map(x=>({passed:x.passed,count:x.checks.length})), 'scope:',audit.passed);
